name: first try file

on:
  push:
    branches:
      - test-environment

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tools/integration/srs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript file
        run: tsc try.ts

      - name: Run compiled JavaScript
        run: node try.js